### ISSUE TITLE
Converter error LocalDate cannot be cast to Date

### ISSUE THREAD

**Issue by olayyar** [fdreyfs/vaadin-tuning-datefield#10]
I get the following error, after clicking a day on Calander (locale Germany). I use global converter in my application (GlobalConverterFactory extends DefaultConverterFactory) but this dosn't take effect:

java.lang.ClassCastException: org.joda.time.LocalDate cannot be cast to java.util.Date
    at com.vaadin.data.util.converter.StringToDateConverter.convertToPresentation(StringToDateConverter.java:37) ~[vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.data.util.converter.ConverterUtil.convertFromModel(ConverterUtil.java:94) ~[vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.ui.AbstractField.convertFromModel(AbstractField.java:708) ~[vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.ui.AbstractField.convertFromModel(AbstractField.java:693) ~[vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.ui.AbstractField.setConvertedValue(AbstractField.java:824) ~[vaadin-server-7.2.5.jar:7.2.5]
    at org.vaadin.addons.tuningdatefield.TuningDateField.onCalendarItemClicked(TuningDateField.java:986) ~[tuning-datefield-0.14.0.jar:0.14.0]
    at org.vaadin.addons.tuningdatefield.TuningDateField$3.calendarItemClicked(TuningDateField.java:366) ~[tuning-datefield-0.14.0.jar:0.14.0]
    at sun.reflect.GeneratedMethodAccessor529.invoke(Unknown Source) ~[na:na]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:295) [vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:188) [vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408) [vaadin-server-7.2.5.jar:7.2.5]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:237) [vaadin-server-7.2.5.jar:7.2.5]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
    at ch.qos.logback.classic.selector.servlet.LoggerContextFilter.doFilter(LoggerContextFilter.java:70) [logback-classic-1.0.13.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:542) [jetty-security-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.handler.ContextHandler.__doHandle(ContextHandler.java:1125) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.Server.handle(Server.java:485) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606) [jetty-util-9.2.2.v20140723.jar:9.2.2.v20140723]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535) [jetty-util-9.2.2.v20140723.jar:9.2.2.v20140723]
    at java.lang.Thread.run(Thread.java:745) [na:na]

Best regards
Olay

**Comment by fdreyfs** [comment]
Hi,

Thanks for reporting this.
Are you setting a converter explicitely to the calendar by using tuningDateField.setConverter(StringToDateConverter) or setting null converter ?
By default the TuningDateField uses Joda LocalDate as a model and a custom converter is set by default and it's the one used in priority.
If you want to set you own converter (ex: setConverter(otherConverter) ) make sure it's using Joda LocalDate as a model. You can then get a java.util.Date from this Joda LocalDate easily.

Let me know if this helps you.
If not, could you send me your code snippet .

Regards,

Fred

**Comment by olayyar** [comment]
Hi,
Thanks, but the same error is still there. I think the problem is with the TextField. If i use it without setting the converter explicitly, the problem is with the:  java.lang.ClassCastException: org.joda.time.LocalDate cannot be cast to java.util.Date

I use the component like below:

            final TuningDateField tuningDateField = new TuningDateField(VaadinAppContext.translate("Date.form.preferedDate.caption")+":");                        
            tuningDateField.setLocale(VaadinAppContext.getLocale());
            tuningDateField.setConverter((Converter)new StringToLocalDateConverter());
            tuningDateField.setImmediate(true);
            tuningDateField.setRequired(true);
            tuningDateField.setWeekendDisabled(false);
            tuningDateField.setConvertedValue(LocalDate.now());
...


public class StringToLocalDateConverter implements Converter<String, LocalDate> {

    private static final long serialVersionUID = 1L;

    @Override
    public LocalDate convertToModel(String value, Class<? extends LocalDate> targetType, Locale locale)
            throws Converter.ConversionException {
        if (value == null) {
            return null;
        }
        return LocalDate.parse(value, DateTimeFormat.shortDate().withLocale(locale));
    }

    @Override
    public String convertToPresentation(LocalDate value, Class<? extends String> targetType, Locale locale)
            throws Converter.ConversionException {
        if (value == null) {
            return null;
        }
        return value.toString(DateTimeFormat.shortDate().withLocale(locale));
    }

    @Override
    public Class<LocalDate> getModelType() {
        return LocalDate.class;
    }

    @Override
    public Class<String> getPresentationType() {
        return String.class;
    }
}

**Comment by fdreyfs** [comment]
Hi,

Which version of Vaadin and TuningDateField are you using?

Cheers

**Comment by olayyar** [comment]
Hi,
 
Vaadin 7.2.5 and TuningDateField 0.14.0

Regards

**Comment by olayyar** [comment]
Hi,
an other error, if I enter a date in the TextField:
om.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method dateTextChanged in org.vaadin.addons.tuningdatefield.widgetset.client.TuningDateFieldRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:295) [vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:188) [vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408) [vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:237) [vaadin-server-7.2.5.jar:7.2.5]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
	at ch.qos.logback.classic.selector.servlet.LoggerContextFilter.doFilter(LoggerContextFilter.java:70) [logback-classic-1.0.13.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:542) [jetty-security-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.handler.ContextHandler.__doHandle(ContextHandler.java:1125) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.Server.handle(Server.java:485) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [jetty-server-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606) [jetty-util-9.2.2.v20140723.jar:9.2.2.v20140723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535) [jetty-util-9.2.2.v20140723.jar:9.2.2.v20140723]
	at java.lang.Thread.run(Thread.java:745) [na:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor501.invoke(Unknown Source) ~[na:na]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.2.5.jar:7.2.5]
	... 32 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in org.vaadin.addons.tuningdatefield.TuningDateField$1 failed.
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:984) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1131) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:542) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:445) ~[vaadin-server-7.2.5.jar:7.2.5]
	at org.vaadin.addons.tuningdatefield.TuningDateField$3.dateTextChanged(TuningDateField.java:380) ~[tuning-datefield-0.14.0.jar:0.14.0]
	... 35 common frames omitted
Caused by: com.vaadin.data.util.converter.Converter$ConversionException: Could not convert value to Date
	at com.vaadin.ui.AbstractField.convertToModel(AbstractField.java:748) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.ui.AbstractField.convertToModel(AbstractField.java:725) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.ui.AbstractField.getConvertedValue(AbstractField.java:811) ~[vaadin-server-7.2.5.jar:7.2.5]
	at org.vaadin.addons.tuningdatefield.TuningDateField$1.valueChange(TuningDateField.java:288) ~[tuning-datefield-0.14.0.jar:0.14.0]
	at sun.reflect.GeneratedMethodAccessor425.invoke(Unknown Source) ~[na:na]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.2.5.jar:7.2.5]
	... 42 common frames omitted
Caused by: com.vaadin.data.util.converter.Converter$ConversionException: Could not convert '26.05.2015' to java.util.Date
	at com.vaadin.data.util.converter.StringToDateConverter.convertToModel(StringToDateConverter.java:86) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.data.util.converter.StringToDateConverter.convertToModel(StringToDateConverter.java:37) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.data.util.converter.ConverterUtil.convertToModel(ConverterUtil.java:156) ~[vaadin-server-7.2.5.jar:7.2.5]
	at com.vaadin.ui.AbstractField.convertToModel(AbstractField.java:745) ~[vaadin-server-7.2.5.jar:7.2.5]
	... 48 common frames omitted
![2015_05_21_11_12_29_mozilla_firefox](https://cloud.githubusercontent.com/assets/5063746/7745296/63f21f4a-ffaa-11e4-8856-e7d34eac5353.png)

Regards

**Comment by fdreyfs** [comment]
Hi,
That's very weird, you are the first person coming with these kinds of problems.

I'll try to reproduce with your Vaadin version.
For now I cannot reproduce with your code snippet on Vaadin 7.4.6

Fred

**Comment by olayyar** [comment]
Hi,

thanks. If I am able to solve this problem, let you know..

Olay

**Comment by fdreyfs** [comment]
Hi,
I could reproduce. I'm fixing this error and let you know when it's done.

Regards,

Fred

**Comment by fdreyfs** [comment]
Hi,

Could you try version 0.15.0 which is now available. I could test it against Vaadin 7.2.5 as well.

Here is a code snippet :
```
final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        layout.setSpacing(true);
        setContent(layout);

        final ComboBox comboBox = new ComboBox("Locale : ");
        comboBox.setNullSelectionAllowed(false);
        comboBox.addItem(Locale.FRANCE);
        comboBox.addItem(Locale.US);
        comboBox.addItem(Locale.GERMANY);
        comboBox.setValue(Locale.FRANCE);
        layout.addComponent(comboBox);

        final TextField patternField = new TextField("Pattern : ");
        patternField.setInputPrompt("ex: yyyy/MM/dd");
        patternField.setNullRepresentation("");
        patternField.setImmediate(true);
        layout.addComponent(patternField);

        final TuningDateField tuningDateField = new TuningDateField();
        tuningDateField.setLocale(Locale.GERMANY);
//         tuningDateField.setConverter((Converter)new StringToLocalDateConverter());
        tuningDateField.setImmediate(true);
        tuningDateField.setRequired(true);
        tuningDateField.setWeekendDisabled(false);
        tuningDateField.setConvertedValue(LocalDate.now());
        layout.addComponent(tuningDateField);

        comboBox.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                tuningDateField.setLocale((Locale) comboBox.getValue());
                patternField.setValue(tuningDateField.getDateTimeFormatterPattern());
            }
        });

        patternField.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                tuningDateField.setDateTimeFormatterPattern(patternField.getValue());
            }
        });

        tuningDateField.addValueChangeListener(new ValueChangeListener() {

            @Override
            public void valueChange(ValueChangeEvent event) {
                Notification.show("LocalDate : " + tuningDateField.getLocalDate());

            }
        });
```

**Comment by olayyar** [comment]
Hi,
thanks but the problem is still there. This is maybe application specific problem with my application..
Regards - Olcay

**Comment by fdreyfs** [comment]
Hi,

If you provide me a simple project where the problem appears I may help you solving it.

Regards,

Fre

**Comment by olayyar** [comment]
Hi,

this is a customer migration project (vaadin6 to vaadin7). I have to ask my customer for publishing parts of the project. If he go with me, I will provide you the parts. The problem occurs only in this project. Before using your add-on in this project, I tested it in a simple test-project without error..

Regards - Olay
